services:

  postgres:

    image: postgres:16

    container_name: nutriplanner-postgres

    environment:

      POSTGRES_USER: nutriplanner
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nutriplanner


    ports:

      - "5432:5432"


    volumes:

      - postgres_data:/var/lib/postgresql/data



volumes:

  postgres_data: